name: Solvous
favicon: null
layout_spectrum: 0.70306
typography_spectrum: 0.60572
title: Solvous Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005870'
    - '#b3cdd4'
    - '#4b899a'
    - '#8bb3be'
  brandStrength: 0
  lightness: 0.46910070814192295
  saturation: 0.6301278048194945
  rhythmicContrast: 0.3180090459063649
purpose: []
